export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const DELETE_PHOTO = 'DELETE_PHOTO';
export const ALL_PHOTOS = 'ALL_PHOTOS';
export const FIRST_PHOTOS = 'FIRST_PHOTOS';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SELECTED_UPLOADER = 'SELECTED_UPLOADER';
export const MORE_PHOTOS = 'MORE_PHOTOS';
export const SINGLE_VIEW = 'SINGLE_VIEW';
export const COMMENT_UPLOADER = 'COMMENT_UPLOADER';
export const INDIV_COMMENTS = 'INDIV_COMMENTS';
export const DELETE_PHOTO_COMMENTS = 'DELETE_PHOTO_COMMENTS';

